<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1577739084174' stop='1577739084175'>
    <name>#Arithmatic Operations #multiplication()</name>
    <title>#Arithmatic Operations #multiplication()</title>
    <test-cases>
        <test-case start='1577739084174' status='passed' stop='1577739084175'>
            <name>should mutiply two numbers</name>
            <title>should mutiply two numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1577739084175' status='failed' stop='1577739084175'>
            <name>should mutiply multiple numbers</name>
            <title>should mutiply multiple numbers</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>expected 120 to equal 121</message>
                <stack-trace>AssertionError: expected 120 to equal 121
                    at Context.&lt;anonymous> (test/sample-test2.js:20:55)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>